[server]
maxUploadSize = 1

# theme: nord-light
[theme]
base = 'light'
primaryColor = '#5E81AC'
backgroundColor = '#ECEFF4'
secondaryBackgroundColor = '#E5E9F0'
textColor = '#2E3440'

font = 'monospace'